name: Linting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 2.2.0

    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Install project
      run: poetry install --no-interaction

    - name: Run linting
      run: |
        poetry run python -m pip install black isort flake8
        poetry run black --check imginspecthub/
        poetry run isort --check-only imginspecthub/
        poetry run flake8 imginspecthub/ --max-line-length=88 --extend-ignore=E203,W503