name: Nightly Regression Tests

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  regression-tests:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        model: [clip, blip2, llava, minigpt4]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 2.2.0
    
    - name: Install dependencies
      run: poetry install --no-interaction
    
    - name: Create comprehensive test images
      run: |
        poetry run python scripts/create_test_images.py
    
    - name: Test model ${{ matrix.model }} with all operations
      id: test-model
      run: |
        echo "Testing model: ${{ matrix.model }}"
        
        echo "Testing descriptions..."
        for img in regression_test_data/*.jpg; do
          echo "Processing $img with ${{ matrix.model }}"
          poetry run python -m imginspecthub.cli run --model ${{ matrix.model }} --image "$img" --operation description || echo "Failed: $img description"
        done
        
        echo "Testing embeddings..."
        for img in regression_test_data/*.jpg; do
          echo "Processing $img embeddings with ${{ matrix.model }}"
          poetry run python -m imginspecthub.cli run --model ${{ matrix.model }} --image "$img" --operation embedding || echo "Failed: $img embedding"
        done
        
        echo "Testing batch processing..."
        poetry run python -m imginspecthub.cli batch --model ${{ matrix.model }} --directory regression_test_data --operations description,embedding --output batch_results_${{ matrix.model }}.json || echo "Failed: batch processing"
        
        echo "Model ${{ matrix.model }} testing completed"
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: regression-results-${{ matrix.model }}
        path: |
          regression_test_data/
          batch_results_*.json
        retention-days: 7
    
    - name: Check test results
      if: failure()
      run: |
        echo "Tests failed for model ${{ matrix.model }}"
        exit 1

  test-summary:
    runs-on: ubuntu-latest
    needs: regression-tests
    if: always()
    
    steps:
    - name: Check overall results
      run: |
        if [[ "${{ needs.regression-tests.result }}" == "failure" ]]; then
          echo "Some regression tests failed"
          exit 1
        else
          echo "All regression tests passed"
        fi
    
    - name: Send failure notification
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.SMTP_USER }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: '[imginspecthub] Nightly Regression Tests Failed'
        to: ${{ secrets.SMTP_USERNAME }}
        from: 'GitHub Actions <${{ secrets.SMTP_USER }}>'
        html_body: |
          <h2>Nightly Regression Tests Failed</h2>
          <p>The nightly regression tests for imginspecthub have failed.</p>
          <p><strong>Repository:</strong> ${{ github.repository }}</p>
          <p><strong>Branch:</strong> ${{ github.ref }}</p>
          <p><strong>Commit:</strong> ${{ github.sha }}</p>
          <p><strong>Workflow:</strong> ${{ github.workflow }}</p>
          <p><strong>Run ID:</strong> ${{ github.run_id }}</p>
          <p><a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">View failed workflow run</a></p>
          <hr>
          <p>Please check the workflow logs for detailed error information.</p>