name: CLI Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 2.2.0
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Install project
      run: poetry install --no-interaction

    - name: Test CLI functionality
      run: |
        poetry run python -m imginspecthub.cli --help
        poetry run python -m imginspecthub.cli models
        poetry run python -m imginspecthub.cli info